### ISSUE TITLE
Feedback for Travis CI C# support

### ISSUE THREAD

**Issue by akoeplinger** [mexx/FSharp.Core.NextVersion.Shim#6]
Hey, I'm one of the contributors of the [Travis CI C# support](http://blog.travis-ci.com/2014-12-10-community-driven-language-support-comes-to-travis-ci/) and saw that you enabled it on your repository.

I'd be really interested to hear how your experience was. Is the [documentation](http://docs.travis-ci.com/user/languages/csharp/) easy to understand? Can we improve something? Did you encounter any problems?

Thanks for your time :smile:

**Comment by mexx** [comment]
Hi @akoeplinger!

It was just a change of few lines in the configuration file.
I'm actually not using the build in `xbuild` with the solution option, this project has a custom build script.

The documentation was easy enough to understand. I only wonder if `solution` setting is required at all in the setup of this project.

Thanks for your efforts to bringing F# and C# support into Travis CI.

**Comment by akoeplinger** [comment]
Thanks for your response!

The `solution` key is totally optional, I've recently added a note to the [docs](http://docs.travis-ci.com/user/languages/csharp/#Overview) about that:

> When the solution key is present, Travis will run NuGet package restore and build the given solution. You can also specify your own scripts, as shown in the next section.
